<a href="https://colab.research.google.com/github/SujalGodse/Pratical_Machine_Learning-PML-/blob/main/PML_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression


import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

In [6]:
from sklearn.linear_model import LinearRegression

df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx', sheet_name = 'stackloss')
x_train, x_test, y_train, y_test = train_test_split(df.drop('StackLoss', axis=1),df.StackLoss, test_size=0.1, random_state=20)

# Creating an instance for the function
regr1 = LinearRegression()

regr1.fit(x_train,y_train)

print(regr1.intercept_)
print(regr1.coef_)
print(regr1.feature_names_in_)

-33.281344575611186
[ 0.70013521  1.34985785 -0.22974125]
['AirFlow' 'WaterTemp' 'AcidConc']

## **For Standardization in Linear Regression**

when we perform linear regression using SKLearn then we perform standardization because

- Easier Coefficient Interpretation

- Features May Have Very Different Scales

# **Different Scalers in Scikit-Learn**

### **Standard Scaler**

In [7]:
from sklearn.preprocessing import StandardScaler
scl = StandardScaler()

# fitting will only be done on training data not on test data
x_train = scl.fit_transform(x_train)
x_test = scl.transform(x_test)

# as x_train and x_test are in array we will convert them into DF
x_train = pd.DataFrame(x_train, columns = ['AirFlow','WaterTemp','AcidConc'])
x_test = pd.DataFrame(x_test, columns = ['AirFlow','WaterTemp','AcidConc'])

regr2 = LinearRegression()
regr2.fit(x_train,y_train)

print(regr2.intercept_)   # intercept
print(regr2.coef_)    # coefficients
print(regr2.feature_names_in_)

18.666666666666668
[ 6.19332814  4.40861726 -0.90286981]
['AirFlow' 'WaterTemp' 'AcidConc']

### **Standard Scaler**

- Manually we can perform using formula : x - xbar / std

In [8]:
df = pd.DataFrame({'Values':[3,6,5,1,6,8,3,8,9,4]})

df['StdScale'] = (df.Values-np.mean(df.Values))/np.std(df.Values,ddof=1)
df

   Values  StdScale
0       3 -0.890045
1       6  0.270883
2       5 -0.116093
3       1 -1.663997
4       6  0.270883
5       8  1.044835
6       3 -0.890045
7       8  1.044835
8       9  1.431811
9       4 -0.503069

### **MinMax Scaler**  

Formula : (x - min(x)) / (max(x) - min(x))

- values are between 0 and 1

- insure there is no outlier and if outliers are present then use robust scaler

In [9]:
# by using manually
df['MinMax'] = (df.Values-min(df.Values))/(max(df.Values)-min(df.Values))
df

   Values  StdScale  MinMax
0       3 -0.890045   0.250
1       6  0.270883   0.625
2       5 -0.116093   0.500
3       1 -1.663997   0.000
4       6  0.270883   0.625
5       8  1.044835   0.875
6       3 -0.890045   0.250
7       8  1.044835   0.875
8       9  1.431811   1.000
9       4 -0.503069   0.375

In [10]:
# by using inbuilt calculation
from sklearn.preprocessing import MinMaxScaler
scl = MinMaxScaler()

### **Robust Scaler**

Formula : (x-median(col))/percentile(col,75)-percentile((col,75))  
**x - median / IQR**

In [11]:
# by using manually
df['Robust'] = (df.Values-np.median(df.Values))/(np.percentile(df.Values,75)-np.percentile(df.Values,25))
df

   Values  StdScale  MinMax    Robust
0       3 -0.890045   0.250 -0.588235
1       6  0.270883   0.625  0.117647
2       5 -0.116093   0.500 -0.117647
3       1 -1.663997   0.000 -1.058824
4       6  0.270883   0.625  0.117647
5       8  1.044835   0.875  0.588235
6       3 -0.890045   0.250 -0.588235
7       8  1.044835   0.875  0.588235
8       9  1.431811   1.000  0.823529
9       4 -0.503069   0.375 -0.352941

In [12]:
# by using in built calculation
from sklearn.preprocessing import RobustScaler

- StandardScaler

Centers data around 0 and scales it to unit variance using mean and standard deviation.

- MinMaxScaler

Scales data to a fixed range, usually 0 to 1, using minimum and maximum values.

- RobustScaler

Scales data using the median and interquartile range, making it resistant to outliers.

---

- StandardScaler

→ Mean & Standard Deviation

- MinMaxScaler

→ Minimum & Maximum
→ Output between 0 and 1

- RobustScaler

→ Median & IQR
→ Best for Outliers

## **Response is Continuous and Predictor is categorical and continuous both**

For this we will do Dummy Encoding

In [13]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx', sheet_name = 'salaries')
df = df[['yrs_service','gender','salary']]
df.head()

   yrs_service gender  salary
0           18   Male  139750
1           16   Male  173200
2            3   Male   79750
3           39   Male  115000
4           41   Male  141500

In [14]:
gender_dum = pd.get_dummies(df.gender,drop_first=True).astype(int)
gender_dum.head()

   Male
0     1
1     1
2     1
3     1
4     1

In [15]:
df = pd.concat([df,gender_dum], axis=1)
print(df)

df = df.drop('gender', axis=1)
df

     yrs_service gender  salary  Male
0             18   Male  139750     1
1             16   Male  173200     1
2              3   Male   79750     1
3             39   Male  115000     1
4             41   Male  141500     1
..           ...    ...     ...   ...
392           30   Male  103106     1
393           19   Male  150564     1
394           25   Male  101738     1
395           15   Male   95329     1
396            4   Male   81035     1

[397 rows x 4 columns]

     yrs_service  salary  Male
0             18  139750     1
1             16  173200     1
2              3   79750     1
3             39  115000     1
4             41  141500     1
..           ...     ...   ...
392           30  103106     1
393           19  150564     1
394           25  101738     1
395           15   95329     1
396            4   81035     1

[397 rows x 3 columns]

In [16]:
# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('salary', axis=1),df.salary, test_size=0.2, random_state=20)

In [17]:
# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

In [18]:
# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     21.52
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           1.75e-09
Time:                        11:51:28   Log-Likelihood:                -3698.4
No. Observations:                 317   AIC:                             7403.
Df Residuals:                     314   BIC:                             7414.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
yrs_service   701.6382    125.946      5.571      0.000     453.834     949.442
Male         1.368e+04   5434.664      2.517      0.012    2985.362    2.44e+04
const        8.857e+04   5285.500     16.757      0.000    7.82e+04     9.9e+04
==============================================================================
Omnibus:                       28.103   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.160
Skew:                           0.696   Prob(JB):                     3.82e-08
Kurtosis:                       3.804   Cond. No.                         99.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

from above output:

H0 : with respect to female (reference event) if the male is selected then it does not influence the salary.

H0 : For the row of constant H0 : c=0

p-value = 0

decision : since the p value is 0 we reject H0

conclusion : constant term influences salary

effect : effect is significant c = 88570 indicates the salary of a person for whom yer_service = 0 and male =0 which means that the gender is female

the staritng salary for the males = 88570 + 13680

### **Response Variable	Predictor Variable(s)	Method**

Continuous	One continuous	Simple Linear Regression

Continuous	Multiple continuous	Multiple Linear Regression

Continuous	Only categorical (2 groups)	t-test

Continuous	Only categorical (3+ groups)	ANOVA

Continuous	Mix of categorical and continuous	Multiple Linear Regression (with dummy variables)

Categorical	Any predictors	Logistic Regression

## **PROBLEM SoLVING**

In [24]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/Marks.xlsx')
df.head()

    Subject Trainer  Marks
0  Calculus  Sudeep     65
1  Calculus  Sudeep     75
2  Calculus  Sudeep     86
3  Calculus  Sudeep     82
4  Calculus  Sudeep     75

## **Problem On Sales Data**

In [26]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/SalesData.xlsx')


region_dum = pd.get_dummies(df['Region'],drop_first=True).astype(int)

df = pd.concat([df,region_dum], axis=1)

df = df.drop('Region', axis=1)

print(df.head())

# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('Sales', axis=1),df.Sales, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

        Sales  Ad_Budget  Store_Size  North  South  West
0  268.093732         44        2836      0      0     0
1  441.660841         96        2656      1      0     0
2  347.500444         76         615      1      0     0
3  297.618111         64        2036      0      0     1
4  203.849511         24        2211      0      0     0
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.888
Model:                            OLS   Adj. R-squared:                  0.887
Method:                 Least Squares   F-statistic:                     1889.
Date:                Thu, 04 Jun 2026   Prob (F-statistic):               0.00
Time:                        12:20:17   Log-Likelihood:                -5940.0
No. Observations:                1200   AIC:                         1.189e+04
Df Residuals:                    1194   BIC:                         1.192e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Ad_Budget      3.4866      0.037     93.243      0.000       3.413       3.560
Store_Size     0.0185      0.001     24.302      0.000       0.017       0.020
North         -4.0818      2.830     -1.442      0.149      -9.634       1.471
South         10.7994      2.770      3.899      0.000       5.365      16.234
West          -5.9182      2.768     -2.138      0.033     -11.349      -0.488
const         68.6151      3.535     19.409      0.000      61.679      75.551
==============================================================================
Omnibus:                        4.762   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.092   Jarque-Bera (JB):                3.820
Skew:                          -0.010   Prob(JB):                        0.148
Kurtosis:                       2.724   Cond. No.                     1.41e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.41e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

## **The constant term indicates the value of response when all the continuous term are = 0 and the categorical variables are set at their reference level or are equal to reference level.**